services:
    laravel_app:
        container_name: laravel_app
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "9000:80"
        env_file:
            - .env
        volumes:
            - .:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
        restart: always
        networks:
            - gp-shared-net

networks:
    gp-shared-net:
        external: true
